//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UP._01._01
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookGener
    {
        public int ID { get; set; }
        public int IdBook { get; set; }
        public int IdGener { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Gener Gener { get; set; }
    }
}
